describe("Test Registration Form Behavior", () => {
    it("passes", () => {
        cy.visit("/en/auth/flow/register")
        cy.get("input[name='name']").type("y")
        cy.get("input[name='email']").type("yyyy")
        cy.get("input[name='password']").type("xxxx")
        cy.get("input[name='confirmPassword']").type("xxxyyyyyyyyyyx", { force: true })
        cy.get("button[type='submit']").click({ force: true })
        cy.contains("Invalid email")
        cy.contains("Password must be at least 8 characters")
        cy.contains("Passwords do not match")
        cy.contains("Weak")

        cy.intercept('POST', '/en/auth/flow/register').as('registerRequest')

        cy.get("input[name='name']").clear().type("test name")
        cy.get("input[name='email']").clear().type("ali@gmail.com")
        cy.get("input[name='password']").clear().type("abcDEF123+")
        cy.get("input[name='confirmPassword']").clear().type("abcDEF123+", { force: true })
        cy.get("button[type='submit']").click({ force: true })
        cy.wait('@registerRequest')
        cy.get("[data-testid='toast-message']").should("be.visible")
    })
    it("passes", () => {
        cy.visit("/ar/auth/flow/register")
        cy.get("input[name='name']").type("s")
        cy.get("input[name='email']").type("ysyy")
        cy.get("input[name='password']").type("xsxx")
        cy.get("input[name='confirmPassword']").type("xxxyyyysyyyyyx", { force: true })
        cy.get("button[type='submit']").click({ force: true })
        cy.contains("البريد الإلكتروني غير صالح")
        cy.contains("يجب أن تكون كلمة المرور مكونة من 8 أحرف على الأقل")
        cy.contains("كلمات المرور غير متطابقة")
        cy.contains("ضعيف")

        cy.intercept('POST', '/ar/auth/flow/register').as('registerRequest')

        cy.get("input[name='name']").clear().type("test name")
        cy.get("input[name='email']").clear().type("ali@gmail.com")
        cy.get("input[name='password']").clear().type("abcDEF123+")
        cy.get("input[name='confirmPassword']").clear().type("abcDEF123+", { force: true })
        cy.get("button[type='submit']").click({ force: true })
        cy.wait('@registerRequest')
        cy.get("[data-testid='toast-message']").should("be.visible")
    })
    it("passes", () => {
        cy.visit("/fr/auth/flow/register")
        cy.get("input[name='name']").type("r")
        cy.get("input[name='email']").type("yyry")
        cy.get("input[name='password']").type("xrxx")
        cy.get("input[name='confirmPassword']").type("xxxyyryyyyyyyx", { force: true })
        cy.get("button[type='submit']").click({ force: true })
        cy.contains("Email invalide")
        cy.contains("Le mot de passe doit comporter au moins 8 caractères")
        cy.contains("Les mots de passe ne correspondent pas")
        cy.contains("Faible")

        cy.intercept('POST', '/fr/auth/flow/register').as('registerRequest')

        cy.get("input[name='name']").clear().type("test name")
        cy.get("input[name='email']").clear().type("ali@gmail.com")
        cy.get("input[name='password']").clear().type("abcDEF123+")
        cy.get("input[name='confirmPassword']").clear().type("abcDEF123+", { force: true })
        cy.get("button[type='submit']").click({ force: true })
        cy.wait('@registerRequest')
        cy.get("[data-testid='toast-message']").should("be.visible")

    })
})